name: EvoluPets
main: fr.aarize.evolupets.EvoluPets
version: 2.0
api-version: "1.20"
author: Aarize
depend: [Vault]

commands:
  pet:
    description: Gérer les pets (gui/summon/dismiss/info)
    usage: /pet [gui|summon|dismiss|info|give|reload|balance]

permissions:
  evolupets.admin:
    description: Admin EvoluPets (give, reload)
    default: op
